# server nginx ref: https://nginx.org/en/docs/beginners_guide.html

## context events digunakan untuk konfigurasi koneksi worker. di konfigurasi ini tidak ada pengaturan tambahan, tapi block events tetap wajib ada
events {}
## tapi block events tetap wajib ada.
http {
    ## biki virtual host atau satu server block atau kalo di documentation: satu server block yang mewakili satu virtual host
    server {
        ## port yg akan di baca nginx server
        listen 80;
        ## arah document root tempat NGINX mencari file yang diminta browser
        root /usr/share/nginx/html;
        ## mencoba mencari file sesuai request:
        ## 1. $uri > file yang diminta
        ## 2. $uri/ > jika berupa direktori
        ## 3. /index.html -> jika tidak ditemukan
        ## Konfigurasi yang diperlukan untuk SPA
        ## sehingga request seperti /login atau /profile tidak menghasilkan eror
        ## melainkan dikembalikan ke index.html agar react router yg handle
        index index.html;
        location / {
            try_files $uri $uri/ /index.html;
        }

    }

}