name: Automation Tasks

on:
  push:
    tags:
      - v*

jobs:
  # Quality Gate bertugas mengecek apakah project ini benar2 bisa di build
  check:
    name: Check
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.ref }}

    steps:
      - name: Checkout Repository
      ## Mengambil source code repository ke GitHub Runner (sama dengan git clone), cuma ini di lakukan oleh github runner
        uses: actions/checkout@v4

      - name: Setup Node.js
      # menginstall env Node.js versi 24 pada GitHub Runner.
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Dependencies ( Node_modules )
      # pakai ci karna CI/CD, dan ini lebih bast practice, ringan juga jadi Lebih cepat dan konsisten karena menggunakan package-lock.json
        run: npm ci

      # - name: Lint
      #   run: npm run lint

      - name: Build
      # bikin /dist. sama kaya Dockerfile, bedanya docker membuat di container sedangkan github membuat di runner
        run: npm run build

      - name: Upload Artifact
      # bikin artifact sementara ( sama kaya zip ) sementara, kalo docker bikin images github bikin artifact sementara sementara yg di simpan di github  biar job selanjutnya ga perlu build lagi
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          if-no-files-found: error

  release:
    name: Release
    needs: check
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Artifact
      # download artifact yg sebelumnya dari github dan menghasilkan /dist
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Create GitHub Release
      # job ini membuat GitHub Release berdasarkan tag yang sudah di-push, Release note dibuat otomatis
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true

      - name: Login to GHCR
      # login ke github container, agar docker images bisa di push
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker Metadata
      # ini job menghasilkan metadata Docker seperti tag dan label secara otomatis.
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}

      - name: Build & Push Docker Image
      # Build Docker Image berdasarkan Dockerfile, kemudian push image ke GitHub Container Registry.
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    name: Deploy
    needs: release
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{ secrets.SSH_KEY }}

          # mengambil Docker Image terbaru dari GHCR ke VPS
          # menghapus container lama jika masih ada, || (OR) true agar workflow tidak gagal jika container ga ada
          # menjalankan container baru, Port VPS 9802 dibuka / diteruskan port 80 di dalam container nginx
          script: |
            docker pull ghcr.io/${{ github.repository }}:latest
            docker container rm frontend --force || true
            docker run -d -p 9802:80 --name frontend ghcr.io/${{ github.repository }}:latest